### PR TITLE
tools.sh: increased number of retries

### PR DESCRIPTION
**Pull request by redbeam**
Increasing the number of retries should help with various issues during setup (i.e. waiting for cert renewal, getting pods...).

### CODE REVIEW

**Comment by redbeam** [comment]
This will go to release-4.16, but the plan is to have it merged to release-4.17 and master as well.

**Comment by cfergeau** [comment]
are you testing on a not so powerful machine? or is this openshift which got slower because it's doing more things?

**Comment by redbeam** [comment]
I'm doing the testing on GCP, I don't know how powerful it is compared to the pipeline runners.

**Comment by cfergeau** [comment]
ok, no objection from my side if this helps, let's wait for feedback from Praveen though!

**Comment by redbeam** [comment]
Well, it's mainly because of #946 and #947, which both failed due to cert renewal not finishing in time (and the script running out of retries). There are probably some differences between master and 4.17, and 4.16 branches, which make the former fail.

**Comment by praveenkumar** [comment]
@redbeam should we create this PR against master or release-4.17 branch where the CI is failing instead this branch where CI already green. Better to cherry-pick this commit to either #946 or #947 and see if CI succeed.

**Pull request merged**
