### PR TITLE
Add capabilities for 4.12

### PR DESCRIPTION
**Pull request by praveenkumar**

### CODE REVIEW

**Comment by cfergeau** [comment]
What are the differences before/after this PR? do we have exactly the same operators enabled/disabled? or are there more/less operators disabled? Would this change how we enable the monitoring stack for example?

**Comment by cfergeau** [comment]
> Yes as of now we have exactly same operators are disabled as we have now.

This would be useful to have in the commit log to know there are no expected behaviour changes from this PR.

By the way, the end result is a mix of capabilities + cvo override, what do we gain from this?

**Comment by praveenkumar** [comment]
> By the way, the end result is a mix of capabilities + cvo override, what do we gain from this? It seems more complex than before?

@cfergeau Right now it is mix with capabilities + cvo but moving forward it will be only capability if you check after this PR I think we only have override for monitoring and some MCO side other that that everything handled by capability and may be soon monitoring also become part of capability.

**Comment by cfergeau** [comment]
> > By the way, the end result is a mix of capabilities + cvo override, what do we gain from this? It seems more complex than before?
> 
> @cfergeau Right now it is mix with capabilities + cvo but moving forward it will be only capability if you check after this PR I think we only have override for monitoring and some MCO side other that that everything handled by capability and may be soon monitoring also become part of capability.

Are there bugs/enhancements/... tracking the use of capabilities for monitoring/... ?

**Comment by praveenkumar** [comment]
> > > By the way, the end result is a mix of capabilities + cvo override, what do we gain from this? It seems more complex than before?
> > 
> > 
> > @cfergeau Right now it is mix with capabilities + cvo but moving forward it will be only capability if you check after this PR I think we only have override for monitoring and some MCO side other that that everything handled by capability and may be soon monitoring also become part of capability.
> 
> Are there bugs/enhancements/... tracking the use of capabilities for monitoring/... ?

https://issues.redhat.com/browse/MON-2854

**Review by cfergeau — APPROVED** [review]

**Pull request merged**
