### PR TITLE
Use ${SNC_PRODUCT_NAME}.${BASE_DOMAIN} instead of crc.testing

### PR DESCRIPTION
**Pull request by eranco74**
This will create the currect registry-certs configmap incase the user changed the default SNC_PRODUCT_NAME or BASE_DOMAIN

### CODE REVIEW

**Comment by cfergeau** [comment]
A similar change will be needed in `microshift.sh` once it lands. Otherwise, this makes sense to me!

**Comment by praveenkumar** [comment]
> A similar change will be needed in microshift.sh once it lands. Otherwise, this makes sense to me!

@cfergeau you mean as part of hostname `sed -i '/--bootproto=dhcp/a\network  --hostname=api.crc.testing' scripts/image-builder/config/kickstart.ks.template`  or some other place?

**Comment by cfergeau** [comment]
> > A similar change will be needed in microshift.sh once it lands. Otherwise, this makes sense to me!
> 
> @cfergeau you mean as part of hostname `sed -i '/--bootproto=dhcp/a\network --hostname=api.crc.testing' scripts/image-builder/config/kickstart.ks.template` or some other place?

yes this one

**Comment by eranco74** [comment]
e2e-snc failed due to:
`
Suite run returned error: AlertErr: services "prometheus-k8s" not found
`
 which is a bit strange since we ddon't expect prometheus to run on CRC, perhaps this test should be excluded from the test suite?

**Comment by praveenkumar** [comment]
> which is a bit strange since we ddon't expect prometheus to run on CRC, perhaps this test should be excluded from the test suite?

@eranco74 yes some of the test cases are obsolete and need to be removed from CI side.

**Pull request merged**
