### PR TITLE
disable monitor tests

### PR DESCRIPTION
**Pull request by redbeam**
#944

### CODE REVIEW

**Comment by praveenkumar** [comment]
CI is still not green, does that mean, it still have something missing?

**Comment by praveenkumar** [comment]
we have  a green CI run 👍🏼

**Comment by praveenkumar** [comment]
In the commit logs let's put more details around why we are disabling those monitor logs.

**Comment by redbeam** [comment]
> In the commit logs let's put more details around why we are disabling those monitor logs.

Alright, so something like:
```
Disabling monitor tests that prevent the test from passing. These tests are not needed because...
```
?

**Comment by gbraad** [comment]
Is this because we disable Monitoring during deployment?

**Pull request merged**
