### PR TITLE
Rename route_controller.yaml.in to router-controller.yaml.in

### PR DESCRIPTION
**Pull request by praveenkumar**

### CODE REVIEW

**Review by cfergeau — COMMENTED** [review]
Maybe document that:
- this is more consistent with the naming of the container image
- this allows to workaround a problem with bundle v4.13.xx which had an invalid route_controller.json file

**Comment by praveenkumar** [comment]
@cfergeau updated the commit log.

**Review by cfergeau — APPROVED** [review]
And I just noticed the new name is wrong in the shortlog :-/ 
`Rename route_controller.yaml.in to router-controller.yaml.in` (it's 'routes-controller.yaml.in')

Apart from that, ACK.

**Pull request merged**
